---
- name: install prometheus-postgres-exporter
  package:
    name: prometheus-postgres-exporter
    state: present
  tags:
    - role::prometheus-postgres-exporter

- name: create postgres user for prometheus
  become: true
  become_user: postgres
  community.postgresql.postgresql_user:
    name: prometheus
    conn_limit: 5
    state: present
  tags:
    - role::prometheus-postgres-exporter

- name: grant user membership to pg_monitor
  become: true
  become_user: postgres
  community.postgresql.postgresql_membership:
    user: prometheus
    groups: [pg_monitor]
    state: exact
  tags:
    - role::prometheus-postgres-exporter

- name: configure prometheus-postgres-exporter
  lineinfile:
    path: /etc/default/prometheus-postgres-exporter
    regexp: ^DATA_SOURCE_NAME.*
    line: DATA_SOURCE_NAME="user=prometheus host=/run/postgresql dbname=postgres"
    state: present
  notify:
    - restart prometheus-postgres-exporter
  tags:
    - role::prometheus-postgres-exporter
